kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "mongodb.fullname" . }}
  labels:
    billingType: {{ .Values.persistence.billingType }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.claimSize }}
