apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{  .Chart.Name }}-configmap"
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
data:
  mongoUrl: "{{ .Values.config.mongoUrl }}"
  basePath: "{{ .Values.config.basePath }}"
  sessionSecret: "{{ .Values.config.sessionSecret }}"
  nodeEnv: "{{ .Values.config.nodeEnv }}"
