apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{  .Chart.Name }}-configmap"
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
data:
  mongoUrl: "{{ .Values.config.mongoUrl }}"
  basePath: "{{ .Values.config.basePath }}"
  sessionSecret: "{{ .Values.config.sessionSecret }}"
  nodeEnv: "{{ .Values.config.nodeEnv }}"
  signupEndpoint: "/api/user/create"
  loginEndpoint: "/api/user/authenticate"
  getUsersEndpoint: "/api/user/get"
  getBillsEndpoint: "/api/bills/get"
  upsertBillEndpoint: "/api/bills/create"
  dropBillsEndpoint: "/api/bills/drop"
  createAccountEndpoint: "/api/accounts/create"
  getAccountsEndpoint: "/api/accounts/get"
  accountWithdrawEndpoint: "/api/accounts/withdraw"
  accountDepositEndpoint: "/api/accounts/deposit"
  dropAccountsEndpoint: "/api/accounts/drop"
  createTransactionEndpoint: "/api/transactions/create"
  getTransactionsEndpoint: "/api/transactions/get"
  dropTransactionsEndpoint: "/api/transactions/drop"
  chatEndpoint: "/api/message"
